export interface Template {
  cat: string;
  title: string;
  text: string;
}

export const templates: Template[] = [
  { cat: 'coding', title: 'Debug Assistant', text: 'You are an expert software debugger. Given the following code and error message, identify the root cause, explain why it occurs, and provide a corrected version with comments explaining the fix.\n\nCode:\n[paste code]\n\nError:\n[paste error]\n\nOutput: Corrected code block + explanation.' },
  { cat: 'coding', title: 'Code Reviewer', text: 'You are a senior software engineer conducting a code review. Analyze the following code for: bugs, performance issues, security vulnerabilities, readability, and adherence to best practices. Format your response as a numbered list of findings, each with severity (High/Medium/Low) and a suggested fix.' },
  { cat: 'coding', title: 'Function Generator', text: 'You are a [language] developer. Write a well-commented function that [does X]. Requirements: handle edge cases, include error handling, follow [language] best practices, and provide a usage example at the end.' },
  { cat: 'writing', title: 'Blog Post Writer', text: 'You are an expert content writer. Write a [word count]-word blog post about [topic] for [target audience]. Use a [tone] tone. Structure: engaging hook → 3-4 main sections with subheadings → actionable conclusion. Optimize for readability and SEO. Avoid jargon.' },
  { cat: 'writing', title: 'Email Drafter', text: 'You are a professional communications expert. Draft a [formal/casual] email from [sender role] to [recipient role] about [subject]. Goal: [desired outcome]. Tone: [tone]. Keep it concise — no longer than [length]. Include a clear subject line.' },
  { cat: 'writing', title: 'Technical Documentation', text: 'You are a technical writer. Create clear documentation for [feature/API/system]. Include: overview, prerequisites, step-by-step instructions, code examples, common errors and fixes, and a FAQ section. Target audience: [developer level].' },
  { cat: 'analysis', title: 'Data Analyst', text: 'You are a senior data analyst. Analyze the following data and provide: key trends and patterns, notable anomalies or outliers, actionable insights, and 3 specific recommendations. Format as a structured report with an executive summary at the top.\n\nData:\n[paste data]' },
  { cat: 'analysis', title: 'Competitive Analysis', text: 'You are a market research specialist. Conduct a competitive analysis comparing [Company A] and [Company B] across: product features, pricing, target market, strengths, weaknesses, and market positioning. Output as a structured comparison table followed by strategic insights.' },
  { cat: 'analysis', title: 'Root Cause Analysis', text: 'You are a problem-solving expert using the 5-Why methodology. Given the following problem, conduct a thorough root cause analysis. Identify the surface symptom, dig through 5 layers of "why," and propose 3 concrete preventive solutions.\n\nProblem: [describe problem]' },
  { cat: 'creative', title: 'Story Worldbuilder', text: 'You are a creative fiction author. Build a detailed world for a [genre] story set in [setting]. Include: geography and climate, societal structure and culture, magic/technology system (with rules and limits), 3 major factions with conflicting goals, and 5 intriguing story hooks. Be vivid and specific.' },
  { cat: 'creative', title: 'Character Creator', text: 'You are a character designer for [medium: novel/game/film]. Create a compelling [archetype] character for a [genre] story. Include: name and physical description, backstory and motivation, core personality traits and flaws, unique skills and abilities, and their role in the narrative.' },
  { cat: 'business', title: 'Business Proposal', text: 'You are a business strategist. Write a compelling one-page business proposal for [idea/product]. Sections: Problem Statement, Proposed Solution, Target Market, Competitive Advantage, Revenue Model, Key Milestones, and Funding Ask. Tone: professional and persuasive.' },
  { cat: 'business', title: 'Meeting Summary', text: 'You are an executive assistant. Transform the following meeting notes into a professional summary. Include: meeting objective, key decisions made, action items (with owner and deadline), open questions, and next steps. Format as a structured document.\n\nNotes:\n[paste notes]' },
];
